# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.cache/wt [current_project]
set_property parent.project_path C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/imports/surse/ssd.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/imports/surse/mpg.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/reg_file.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/InstructionFetch.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/test_env.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/ID.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/UC.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/EX.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/MEM.vhd
  C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/sources_1/new/WB.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/constrs_1/imports/mips/Basys3_test_env.xdc
set_property used_in_implementation false [get_files C:/Users/flore/Desktop/Faculta/AN2_SEM2/AC/mips/mips.srcs/constrs_1/imports/mips/Basys3_test_env.xdc]


synth_design -top test_env -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
